// <auto-generated />
using System;
using FootyAPI.Entities.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FootyAPI.Migrations
{
    [DbContext(typeof(FootyDBContext))]
    [Migration("20181201185430_InitalDBPlan")]
    partial class InitalDBPlan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FootyAPI.Entities.Contexts.Lineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Lineup");
                });

            modelBuilder.Entity("FootyAPI.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionTypeId");

                    b.Property<int>("Minute");

                    b.Property<int>("PlayerId");

                    b.HasKey("Id");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("FootyAPI.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("FootyAPI.Models.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayTeamId");

                    b.Property<int>("CompetitionId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("GameId");

                    b.Property<int>("HomeTeamId");

                    b.Property<string>("Score");

                    b.Property<int>("VenueId");

                    b.HasKey("Id");

                    b.ToTable("Fixture");
                });

            modelBuilder.Entity("FootyAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayScore");

                    b.Property<int>("AwayTeamLinupId");

                    b.Property<int>("HomeScore");

                    b.Property<int>("HomeTeamLinupId");

                    b.Property<int>("ManOftheMatch");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("FootyAPI.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssistPlayerId");

                    b.Property<int>("GameId");

                    b.Property<int>("Minute");

                    b.Property<int>("PlayerId");

                    b.HasKey("Id");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("FootyAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("Number");

                    b.Property<string>("PlayerName")
                        .IsRequired();

                    b.Property<int>("PositionId");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootyAPI.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PositionCategoryId");

                    b.Property<string>("PositionName");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("FootyAPI.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HomePage");

                    b.Property<int?>("HomeVenueId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("HomeVenueId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("FootyAPI.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("FootyAPI.Models.Team", b =>
                {
                    b.HasOne("FootyAPI.Models.Venue", "HomeVenue")
                        .WithMany()
                        .HasForeignKey("HomeVenueId");
                });
#pragma warning restore 612, 618
        }
    }
}
